### ISSUE TITLE
"Open in Vercel"

### ISSUE THREAD

**Issue by alivault** [haydenbleasel/vercel-vscode#71]
Thank you for making this extension! I have one request: to have options added to the command palette for "Open in Vercel:"

- Project
- Deployments
- Current Deployment
- Logs
- Project Settings
- any other links you think would be useful

Similar to the "Open in Github" extension:
![image](https://github.com/haydenbleasel/vercel-vscode/assets/48610822/e3a9a2e6-8c55-4275-b773-94663764bdd5)

**Comment by haydenbleasel** [comment]
Unfortunately AFAIK Vercel don't provide a handy way of getting the dashboard URL from the project and team IDs. I've scoured their APIs, I could probably hack a URL together for team accounts due to the `/v2/teams/${teamId}` endpoint, but there's nothing for individuals due to the lack of `teamId`. I'll pick this up later if Vercel add a `teamSlug` or similar to their `/v9/projects/${projectId}` endpoint.

**Comment by haydenbleasel** [comment]
Closing this until Vercel releases something I can use.

**Comment by alivault** [comment]
Cool. I ended up just using the Vercel extension for Raycast (mac only) and it's been working great for quick access to my deployments.
